Repository harshalhonde21/EcommerceSpectastyle, pull requests merged in 2024-05, with the labels that each got.

#13 Update UI for Login and Signup Pages
  Frontend/.env.local
  Frontend/package.json
  Frontend/src/CSS/Profile.css
  Frontend/src/Pages/Profile.jsx
Labels: Level 2

#86 Implement Secure Password Handling with bcrypt for Signup and Login Functionality
  Backend/Controller/user-controller.js
Labels: Level 1

#101 feat: added issue btns and respective forms
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature.yml
Labels: documentation, Level 1, gssoc

#104 UI - UX Changes + Responsive + Hero Changed
  Frontend/public/arrow.png
  Frontend/public/shoes-image5.png
  Frontend/src/App.jsx
  Frontend/src/CSS/About.css
  Frontend/src/CSS/Cart.css
  Frontend/src/CSS/ConformOrder.css
  Frontend/src/CSS/Contact.css
  Frontend/src/CSS/Footer.css
  Frontend/src/CSS/Home.css
  Frontend/src/CSS/Navbar.css
  Frontend/src/CSS/Product.css
  Frontend/src/CSS/ProductDetail.css
  Frontend/src/CSS/Profile.css
  Frontend/src/CSS/UserProfile.css
  Frontend/src/Components/Footer.jsx
  Frontend/src/Components/Navbar.jsx
  Frontend/src/Pages/About.jsx
  Frontend/src/Pages/Cart.jsx
  Frontend/src/Pages/Contact.jsx
  Frontend/src/Pages/Home.jsx
  Frontend/src/Pages/Product.jsx
  Frontend/src/Pages/Profile.jsx
Labels: good first issue, Level 2, gssoc

#52 made placeOrder page responsive issue#25
  Frontend/src/CSS/PlaceOrder.css
Labels: good first issue, Level 1, gssoc

#126 Feat: adding favicon icon
  Frontend/Mattrich-Adidas-Adidas-Shoe.512.png
  Frontend/index.html
Labels: Level 1, gssoc

#165 fixing typo errors
  Learn.md
Labels: good first issue, Level 1, gssoc

#169 Duplicate Entry of name is deleted from contact form
  Frontend/src/Pages/Contact.jsx
Labels: good first issue, Level1, gssoc

#200 Bug : Multiple Product can click #181
  Frontend/src/CSS/ProductDetail.css
  Frontend/src/Components/ProductDetail.jsx
Labels: bug, Level1, gssoc

#199 Create Contributing.md
  Create Contributing.md
Labels: documentation, Level1, gssoc

#193 Text Overlapping removed
  Frontend/src/CSS/About.css
  Frontend/src/Pages/About.jsx
Labels: Level1, gssoc

#188 Added Scroll to Top Functionality
  Frontend/package-lock.json
  Frontend/src/App.jsx
  Frontend/src/Components/ScrollToTop.jsx
  Frontend/src/main.jsx
Labels: invalid, gssoc

#187 #156 Update README.md it now includes appdesign
  README.md
Labels: Level1, gssoc

#210 Fixed :- #158 Arrow is overlapping with about and products in mobile view
  Frontend/src/CSS/Home.css
Labels: enhancement, good first issue, Level1, gssoc

#215 Product status & Input Bar Changes
  Frontend/src/CSS/Product.css
  Frontend/src/Pages/Product.jsx
Labels: Level1, gssoc

#212 feat:- #159 Enhancement of Navbar (Hovering Effect )
  Frontend/src/CSS/Navbar.css
Labels: Level1, gssoc

#222 when adding same item again to cart, increment the item item quantity. (fixes issue #203)
  Backend/Controller/product-controller.js
  Backend/Models/User.js
Labels: Level2, gssoc

#243 Fix the issue #233 Add logo and add some new styling to home page
  Frontend/public/WebLogo.png
  Frontend/src/CSS/Home.css
  Frontend/src/CSS/Navbar.css
  Frontend/src/Components/Navbar.jsx
  Frontend/src/Pages/Home.jsx
Labels: Level3, gssoc

#273 Adding Fizzy search functionality to search bar
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/Pages/Product.jsx
Labels: Level1, gssoc

#276 Added pull_request_template.md
  .github/pull_request_template.md
Labels: Level1, gssoc

#309 added filters for the products
  Frontend/src/Pages/Product.jsx
Labels: good first issue, Level1, gssoc

#230 solves issue #229
  Frontend/src/CSS/ConformOrder.css
  Frontend/src/Pages/ConformOrder.jsx
Labels: Level2, gssoc

#338 homepageUI #307
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/CSS/Home.css
  Frontend/src/CSS/HomeSecond.css
  Frontend/src/Pages/Home.jsx
  Frontend/src/Pages/HomeSecond.jsx
Labels: Level1, gssoc

#331 cross icon needs to be aligned properly in sidenav bar after click on hamburger.
  Frontend/src/CSS/Navbar.css
Labels: Level1, gssoc

#328 Added back to top button
  Frontend/package-lock.json
  Frontend/src/CSS/Footer.css
  Frontend/src/Components/Footer.jsx
Labels: Level1, gssoc
