Repository harshalhonde21/EcommerceSpectastyle, pull requests merged in 2024-07, with the labels that each got.

#460 fixed cursor appearence below navbar
  Frontend/src/App.css
Labels: level1, gssoc

#467 Feat: Shopping cart icon with count numbers
  Frontend/src/CSS/Navbar.css
  Frontend/src/Components/CartContext.jsx
  Frontend/src/Components/Navbar.jsx
  Frontend/src/Pages/Cart.jsx
Labels: level1, gssoc

#468 Documention update #464
  README.md
Labels: documentation, level1, gssoc

#486 ✔️Implemented a Feedback Page For the Website
  Frontend/src/App.jsx
  Frontend/src/CSS/feedback.css
  Frontend/src/Components/Feedbtn.jsx
  Frontend/src/Pages/Feedback.jsx
  Frontend/src/main.jsx
Labels: level2, gssoc

#476 Title:- Border and hovering effects added to the product cards
  Frontend/src/CSS/Product.css
Labels: level1, gssoc

#477 Fix for CartItems number Update issue
  Frontend/src/Components/CartContext.jsx
  Frontend/src/Pages/Cart.jsx
Labels: level1, gssoc

#507 Made the user section responsive for mobile view
  Frontend/src/CSS/UserProfile.css
  Frontend/src/Pages/CustomDropdown.css
  Frontend/src/Pages/CustomDropdown.jsx
  Frontend/src/Pages/Product.jsx
Labels: level1, gssoc

#505 Improved Navbar Text Spacing for Better Visibility
  .npmrc
  Frontend/.env
  Frontend/src/CSS/Navbar.css
  Frontend/src/Components/Navbar.jsx
  docker-compose.yml
Labels: level1, gssoc

#500 Enhance the "Trail Effect" and "Hide" in Mobile View
  Frontend/index.html
  Frontend/src/App.css
Labels: level1, gssoc
